# Site settings
title: Wenhu Chen's Home Page
email: wenhuchen@cs.ucsb.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wenhuchen.github.io" # the base hostname & protocol for your site
github: wenhuchen
googlescholar: https://scholar.google.com/citations?user=U8ShbhUAAAAJ&hl=en

# Build settings
markdown: kramdown
